name: deploy-website

on: push

jobs:
  deploy-to-s3:
    name: deploy site to s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      
      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      - name: install dependencies
        run: npm install
      
      - name: build project
        run: npm run build
      
      - name: deploy to s3
        run: aws s3 sync ./dist s3://final-portfolio-website